movieapp/urls.py
from django.urls import path
from .import views
app_name='movieapp'
urlpatterns = [

    path('<slug:c_slug>/', views.AllCategory, name='movie_by_category'),
    path('<slug:c_slug>/<slug:movie_slug>', views.MovieDetail, name='MovieDetail'),
    path('add_movie', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('', views.AllCategory, name='AllCategory'),

]

movieproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from movieproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registerapp/', include('registerapp.urls')),
    path('searchapp/', include('searchapp.urls')),
    path('',include('movieapp.urls')),

]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

registerapp/urls.py
from django.urls import path
from registerapp import views, admin
app_name="registerapp"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),


]

searchapp/urls.py
from django.urls import path
from searchapp import views
app_name='search_app'

urlpatterns = [
    path('',views.SearchQuery,name='SearchQuery'),
]

movieapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here
class Category(models.Model):
    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    poster = models.ImageField(upload_to='category', blank=True)
    class Meta:
        ordering=('title',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('movieapp:movie_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.title)



class Movie(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField()
    desc = models.TextField(blank=True)
    release_date = models.DateField()
    poster= models.ImageField(upload_to='movie',blank=True)
    actor=models.CharField(max_length=100)
    actress=models.CharField(max_length=100)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,null=False)
    ylink=models.URLField(blank=True)
    review=models.TextField(blank=True)
    ratings= models.DecimalField(max_digits=250,decimal_places=1)


    def get_url(self):
        return reverse('movieapp:MovieDetail', args=[self.category.slug, self.slug])

    class Meta:
            ordering = ('name',)
            verbose_name = 'movie'
            verbose_name_plural = 'movies'

    def __str__(self):
        return '{}'.format(self.name)

registerapp/models.py
from django.db import models

# Create your models here.

searchapp/models.py
from django.db import models

# Create your models here.

movieapp/forms.py
from django import forms
from .models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
      model=Movie
      fields=['name','desc','poster',
              'actor','actress','ylink']

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.text import slugify

from movieapp.models import Movie, Category
from .forms import MovieForm
# Create your views here.
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator,EmptyPage,InvalidPage


# Create your views here.
def AllCategory(request,c_slug=None):
    c_page=None
    movie_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        movie_list = Movie.objects.all().filter(category=c_page)
    else:
        movie_list = Movie.objects.all()
    paginator=Paginator(movie_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        movies=paginator.page(page)
    except (EmptyPage,InvalidPage):
        movies=paginator.page(Paginator.num_pages)

    return render(request,'Category.html',{'category':c_page,'movies':movies})
def MovieDetail(request,c_slug,movie_slug):
    try:
        movie=Movie.objects.get(category__slug=c_slug,slug=movie_slug)
    except Exception as e:
        raise e
    return render(request,'movie.html',{'movie':movie})


def add_movie(request):
    if request.method == "POST":
        cat= request.POST.get('category', )
        print(cat)
        category=Category.objects.get(id=cat)
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        release_date = request.POST.get('release_date',)
        poster = request.FILES['poster']
        actor = request.POST.get('actor',)
        actress = request.POST.get('actress',)
        review = request.POST.get('review',)
        ratings = request.POST.get('ratings',)
        m_link=slugify(name)
        ylink = request.POST.get('ylink',)
        movie = Movie(name=name,slug=m_link,desc=desc,release_date=release_date,poster=poster,actor=actor,
                      actress=actress,review=review,ratings=ratings,ylink=ylink,category=category)
        movie.save()
        return redirect('/')
    return  render(request, 'add_movie.html')
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return  render(request,'update.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method == 'POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return  render(request,"delete.html")
#def detail(request,movie_id):
 #    movies=Movie.objects.get(id=movie_id)
  #   return render(request,'movie.html',{'movie':movies})

registerapp/views.py
from audioop import reverse

from django.shortcuts import render
from email import message
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.utils.text import slugify


from movieapp.forms import MovieForm
from movieapp.models import Movie,Category


# Create your views here.

def login(request):

    if request.method=='POST':
       username=request.POST['username']
       password=request.POST['password']
       user=auth.authenticate(username=username,password=password)
       if user is not None:
           auth.login(request,user)
           return redirect('/')
       else:
           messages.info(request, "invalid credentials")
           return redirect('login')

    return render(request,'login.html')
def register(request):
    if request.method=="POST":
        username=request.POST['username']
        first_name=request.POST['first_name']
        last_name=request.POST['last_name']
        email=request.POST['email']
        password=request.POST['password']
        cpassword=request.POST['conpwd']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
               messages.info(request,"Username Taken")
               return redirect("registerapp:register")
            elif User.objects.filter(email=email).exists():
                messages.info(request,"Email taken")
                return redirect("registerapp:register")
            else:
               user=User.objects.create_user(username=username,first_name=first_name,last_name=last_name,password=password,
                                    email=email)
               user.save()
               return redirect("registerapp:login")
        else:
            messages.info(request,"password does n't match")
            return redirect("registerapp:register")
        return redirect('/')
    return render(request,'registration.html')
def logout(request):
    auth.logout(request)
    return redirect('/')

searchapp/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from movieapp.models import Movie
from django.db.models import Q
# Create your views here.
def SearchQuery(request):
    movies=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        movies=Movie.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
    return  render(request,'search.html',{'query':query,'movies':movies})

templates/Category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
     {{category.description|truncatewords:155}}
{% else %}
     Welcome to Vox Cinemas where you can watch your favourite movies
{% endif %}
{% endblock %}
{% block title %}
{% if category %}
     {{category.title}}- Vox Cinemas
{% else %}
      Watch movies Online-Vox Cinemas
{% endif %}
{% endblock %}

{% block content %}
{% if category %}
<div>
<div class="row my-class-row">
      <div class="max-auto">
          <p><a href="{% url 'movieapp:AllCategory' %}">Block Busters</a></p>
      </div>
</div>
</div>
{% endif %}
<div class="max-auto">
    {% if category %}
       <img  class="my_image" src="{{category.poster.url}}" alt="{{category.title}}">
</div>
<br>
<div>
    <p class="text-center my_title">{{category.title}}</p>
    <p class="text-justify" >{{category.desc}}</p>
</div>
{% else %}

    <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="Movies" >

<div>
    <h1 class="text-center my_title">Block Buster Movies</h1>
    <p class="text-center" ></div>
{% endif %}
<div class="container">
    <div class="row mx-auto ">
        {% for movie in movies.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4 ">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{movie.get_url}}"><img class="card-img-top my_image" src="{{movie.poster.url}}" alt="{{movie.name}}" ></a>
                <div class="card-body">
                    <h4>{{movie.name}}</h4>
                    <p>{{movie.release_date}}</p>
                </div>

            </div>
        </div>
        {% endfor %}
    </div>


<div class="mx-auto">
    {% if movies.paginator.num_pages > 1 %}
    <div class="text-center">
        {% for pg in movies.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if movies.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
    </div>
    {% endif %}
</div>
</div>
{% endblock %}

templates/add_movie.html
<h1>You can Add Movie here</h1>
<form method="POST" action="add_movie" enctype="multipart/form-data" >
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name"><br>
    <input type="text" name="slug" placeholder="slug name"><br>

    <input type="text" name="desc" placeholder="enter movie description"><br>
    <input type="date" name="release_date" placeholder="enter release date"><br>
    <input type="text" name="actor" placeholder="enter actor name"><br>
    <input type="text" name="actress" placeholder="enter actress name"><br>
    <select name="category" class="form-control">
        {% for c in links %}
            <option value="{{c.id}}">{{c.title}}</option>

        {% endfor %}
    </select>
    <input type="file" name="poster"><br>
    <input type="text" name="review" placeholder="write a review"><br>
    <input type="text" name="ratings" placeholder="Your ratings out of 5"><br>

    <input type="url"  name="ylink" placeholder="enter Youtube link"><br>
    <input type="submit" >
</form>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/fonts.googleapis.com/css2' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e7a5f290cb.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}
     <script src="{% static 'js/popper.min.js' %}" ></script>
     <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/delete.html
<form method="POST" >
    {% csrf_token %}
 Are you sure to delete this movie
    <input type ="submit">
</form>

templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Vox Cinemas pvt Ltd.All rights Reserved</p>
</div>

templates/header.html
{%  load static %}
<header>
      <center>
            <a href="{% url 'movieapp:AllCategory'  %}"><img src="{% static 'img/logo.png' %}" alt="logimage" width="200" height="200">
    </center>
</header>

templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
              <img class="card-img-top" src= "{{i.poster.url}}" alt="Card image cap" width="250px" height="250px">
             <div class="card-body">
               <h5 class="card-title">{{i.name}}</h5>
                  <p class="card-text">{{i.release_date}}</p>
                    <a href="{%  url 'movieapp:detail' i.id %}" class="btn btn-primary">view details</a>

             </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}

    <input type ="text" name="username" placeholder="Enter Username"><br>
    <input type ="password" name="password" placeholder="Enter your password"><br>
    <input type ="submit" ><br>
</form>

</body>
</html>

templates/movie.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
     {{movie.description}}
{% endblock %}
{% block title %}
{% if category %}
     {{movie.title}}- Vox Cinemas
{% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'movieapp:AllCategory' %}">Home</a>|<a href="{{movie.category.get_url}}">
            {{movie.category}}</a>|{{movie.title}}</p>

    </div>
    <div class="container">
    <br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{movie.poster.url}}" alt ="{{movie.name}}">
        </div>
    </div>
    <div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
            <h1 class="my_prod_title">{{movie.name}}</h1>
            <p class="text-justify my_prod_text">{{movie.desc}}</p>
                        <h4>Stars In</h4>
            <p class="text-justify my_prod_text">{{movie.actor}}</p>
            <p class="text-justify my_prod_text">{{movie.actress}}</p>
                         <h4>Reviews</h4>
            <p class="text-justify my_prod_text">{{movie.review}}</p>
                         <h4>Ratings</h4>
            <p class="text-justify my_prod_text">{{movie.ratings}}</p>
            <a class="nav_link" href="{{movie.ylink}}">{{movie.ylink}}</a><br><br>
            <a  href="{% url 'movieapp:update' movie.id %}" class="btn btn-success">UPDATE</a>
           <a  href="{% url 'movieapp:delete' movie.id %}" class="btn btn-danger">DELETE</a>

        </div>
    </div>
</div>
  </div>
</div>
</div>

{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Online Movie store</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="True" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
          </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          {% if user.is_authenticated %}
          <li>Hello {{user.username}}</li>
           <li> <a class="nav-link" href="{% url 'registerapp:logout' %}">LOGOUT</a></li>
          <li><a class="nav-link "  href="{% url 'movieapp:add_movie' %}">ADD MOVIE</a></li>


          {% else %}
          <li><a class="nav-link" href="{% url 'registerapp:register' %}">REGISTER</a></li>
          <li><a class="nav-link" href="{% url 'registerapp:login' %}">LOGIN</a></li>

        {% endif%}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            GENRES
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'movieapp:AllCategory' %}">All Categories</a></li>
                      {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.title}}</a></li>
                      {% endfor %}
          </ul>

        </li>

      </ul>
            <form class="d-flex"  action="{% url 'search_app:SearchQuery' %}" method="get">
              {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
               <button class="btn btn-outline-success" type="submit"><i class="fa-brands fa-searchengin"></i></button>
            </form>
    </div>
  </div>
  </div>
</nav>

templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>


    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Registration</h2>
<form action="" method="post">
    {% csrf_token %}
    <input type ="text" name="username" placeholder="Enter Username"><br>
    <input type ="text" name="first_name" placeholder="Enter your first name"><br>
    <input type ="text" name="last_name" placeholder="Enter your last name"><br>
    <input type ="text" name="email" placeholder="Enter Email"><br>
    <input type ="password" name="password" placeholder="Enter password"><br>
    <input type ="password" name="conpwd" placeholder="Confirm Password"><br>
    <input type ="Submit" ><br>


</form>
{% for msg in messages %}
{{msg}}
{% endfor %}
</body>
</html>

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  Best online movie platform
{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content%}
<div>
   <p class="text-center my_search_text">You have searched for:<b>{{query}}</b></p>
</div>
<div class="container">
    <div class="row mx-auto ">
        {% for movie in movies  %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4 ">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{movie.get_url}}"><img class="card-img-top my_image" src="{{movie.poster.url}}" alt="{{movie.name}}" ></a>
                <div class="card-body">
                    <h4>{{movie.name}}</h4>
                    <p>{{movie.desc}}</p>
                </div>

            </div>
        </div>
      {% empty %}
      <div class="row mx_auto">
        <p class="text-center my_search_text">0 results found</p>
      </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/update.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type ="submit">
</form>